#!/usr/bin/env ruby
EXE_FLAG = ARGV[0];
BINARY = "node-template";

project_root = File.expand_path("#{__dir__}/..");

if (EXE_FLAG == "build")
  system("cd #{project_root}; cargo remote -- build --release")
elsif (EXE_FLAG == "clean")
  # this cmd meant to be run in remote dev host
  system("#{project_root}/target/release/#{BINARY} purge-chain --dev && #{project_root}/target/release/#{BINARY} --dev");
else
  # this cmd meant to be run in remote dev host
  system("#{project_root}/target/release/#{BINARY} --dev");
end
